- jutils/jutils.cpp
- src/MediaSync.cpp
memcpy isn't defined in string anymore
> [fix] undeclared identifier memcpy

- src/MediaCodecInfo.cpp
- src/MediaCodecInfo.h
- Add static VP9 profiles (SDK 24)
- Implement CJNIMediaCodecInfoCodecCapabilities::createFromProfileLevel
- fix CJNIMediaCodecInfoCodecCapabilities::profileLevels()
> VP9 for MediaCodecCapabilities / Profiles 

- src/AudioTrack.cpp
- src/AudioTrack.h
Seems to fix the build issue, not sure if the solution is valid otherwise.
```
In file included from /home/ubuntu/libandroidjni/src/AudioTrack.cpp:21:
/home/ubuntu/libandroidjni/src/AudioTrack.h:38:125: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
CJNIAudioTrack(int streamType, int sampleRateInHz, int channelConfig, int audioFormat, int bufferSizeInBytes, int mode) throw(std::invalid_argument);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/libandroidjni/src/AudioTrack.h:38:125: note: use 'noexcept(false)' instead
CJNIAudioTrack(int streamType, int sampleRateInHz, int channelConfig, int audioFormat, int bufferSizeInBytes, int mode) throw(std::invalid_argument);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
noexcept(false) …
```
> fix build with -std=c++17

- src/StorageManager.cpp
StorageManager.getStorageVolumes is available since API level 24. Kodi baseline currently is API level 21.
https://developer.android.com/reference/android/os/storage/StorageManager#getStorageVolumes()
> Check SDK version before calling StorageManager.getStorageVolumes.

- src/MediaCodecInfo.cpp
- src/MediaCodecInfo.h
Adds profile contstants for AV1 hw decoding.
I decided to remove all the Level constants from this PR, because it looks like they're unneeded and we can add them later if necessary.
> Add MediaCodecInfo constants for av1 decoding

- src/Surface.cpp
I should have build tested Fritsch's work first, my bad. This fixes linking with libandroidjni after the setrefreshrate PR
ints need to be declared in the cpp files
added some guards for api 30 for setrefreshrate calls. This may not be necessary (i think the populatestaticfields will be a requirement), but wasnt sure whether its expected to do the checks in the lib, or in the callee. Either way, cant hurt i guess.
> Fix undefined reference link errors in setrefreshrate

- src/MediaCodec.cpp
- src/MediaCodec.h
- src/MediaCodecCryptoInfo.cpp
- src/MediaCodecCryptoInfo.h
- src/MediaCodecCryptoInfoPattern.cpp
- src/MediaCodecCryptoInfoPattern.h
Currently AES-CTR is the only encryption scheme supported for inputstreams in Kodi - it's hardcoded. This change allows for CBC encryption scheme to be used with encrypted content, as CBC requires that a pattern of encrypted/skipped blocks (typically 1,9) be supplied to the CryptoInfo object.
Runtime tested (with required changes in Kodi core - PR coming shortly) on Pixel 3.
> Implement MediaCodec.CryptoInfo.Pattern

- src/DisplayManager.cpp
If CJNIDisplayManager::unregisterDisplayListener is called by Kodi (which is currently not the case, but in future it will to fix another bug), a typo in the jni method descriptor string causes "JNI DETECTED ERROR IN APPLICATION: mid == null" followed by abort(), thus forced Kodi exit.
> DisplayManager: Fix typo in unregisterDisplayListener.

- src/AudioFocusRequest.cpp
- src/AudioFocusRequest.h
- src/AudioManager.cpp
- src/AudioManager.h
API 26 deprecated the existing abandonaudiofocus/requestaudiofocus methods
This PR implements the AudiofocusRequestClass + builder for use with the new abandonAudioFocusRequest/requestaudiofocus methods
abandonAudioFocusRequest - https://developer.android.com/reference/android/media/AudioManager#abandonAudioFocusRequest(android.media.AudioFocusRequest)
requestAudioFocus - https://developer.android.com/reference/android/media/AudioManager#requestAudioFocus(android.media.AudioFocusRequest)
AudioFocusRequest - https://developer.android.com/reference/android/media/AudioFocusRequest
AudioFocusRequest.builder - https://developer.android.com/reference/android/media/AudioFocusRequest.Builder
No real reason other than seemed like something i could use to introduce myself to libandroidjni and …
> [API26+] Implement AudiofocusRequestClass + request/abandonaudiofocus

- src/Bundle.cpp
- src/Bundle.h
- src/Context.cpp
- src/PackageManager.cpp
- src/PackageManager.h
- src/SpeechRecognizer.cpp
- src/SpeechRecognizer.h
Add classes to access the speech recognition service: ```CJNISpeechRecognizer```, ```CJNIRecognitionListener``` and ```CJNIBundle```.
~~Add ```CJNIToast``` to show a brief notifications to the user.~~ 
In ```CJNIContext``` add calls to ```PopulateStaticFields()``` methods.
In ```CJNIPackageManager``` add ```PERMISSION_GRANTED``` and ```PERMISSION_DENIED``` fields.
New classes and changes work perfectly in runtime tests I am doing to incorporate this service in Kodi. 
Tested on Android 9 and 11.
> Access to the speech recognition service

- src/SpeechRecognizer.cpp
- src/SpeechRecognizer.h
We use no namespaces in libandroidjni. So class names should be very specific.
> Rename CJNIRecognitionListener to CJNISpeechRecognitionListener. 

- src/Bitmap.cpp
- src/Canvas.cpp
- src/Canvas.h
- src/Drawable.cpp
- src/Drawable.h
This PR adds the functionality needed for https://github.com/xbmc/xbmc/pull/21423 to libandroidjni - no more, no less.
> Add CJNICanvas. Extend CJNIDrawable, CJNIBitmap.

- src/Context.cpp
- src/MediaCodecList.cpp
- src/MediaCodecList.h
```getCodecCount()``` and ```getCodecInfoAt()``` methods of [MediaCodecList](https://developer.android.com/reference/android/media/MediaCodecList) class are deprecated in API level 21.
Add a constructor and the proposed ```getCodecInfos()``` method to use instead.
Runtime tested with required changes in Kodi.
> MediaCodecList: Add getCodecInfos() method

- src/Activity.h
- src/AudioManager.h
- src/AudioTrack.h
- src/BitmapDrawable.h
- src/Build.h
- src/ConnectivityManager.h
- src/Cursor.h
- src/Display.h
- src/Environment.h
- src/Intent.h
- src/MediaCodec.h
- src/MediaCodecList.h
- src/MediaDrm.h
- src/MediaTimestamp.h
- src/NetworkInfo.h
- src/Notification.h
- src/Os.h
- src/PackageManager.h
- src/PowerManager.h
- src/Resources.h
- src/ScanResult.h
- src/StatFs.h
- src/View.h
- src/WifiConfiguration.h
- src/WifiInfo.h
- src/WifiManager.h
Based on the API documentation I've added the deprecated info in methods and classes where appropriate.
I think it's a good idea to include this info on the library. Allows us to easily identify which methods are deprecated and since when.
> Add deprecated info

- src/MediaFormat.cpp
- src/MediaFormat.h
Add the MediaFormat constants that are being used directly by value in Kodi.
Add the [setFeatureEnabled()](https://developer.android.com/reference/android/media/MediaFormat#setFeatureEnabled(java.lang.String,%20boolean)) method to request a feature to be present or not. Also the [getFeatureEnabled()](https://developer.android.com/reference/android/media/MediaFormat#getFeatureEnabled(java.lang.String)) method if needed.
> Add constants and set feature in MediaFormat

- src/Context.cpp
- src/Window.cpp
- src/Window.h
- src/WindowManager.cpp
- src/WindowManager.h
Add the [FLAG_KEEP_SCREEN_ON](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_KEEP_SCREEN_ON) flag and the necessary methods.
The idea is to use this flag to keep the screen active instead of using a wakelock.
> Add the FLAG_KEEP_SCREEN_ON flag

- src/Context.cpp
- src/Context.h
- src/Resources.cpp
- src/Resources.h
Add `getDrawableForDensity(int id, int density, Resources.Theme theme)` method to replace 
`getDrawableForDensity(int id, int density)` deprecated in API level 22.
This method returns a drawable object associated with a resource ID for the given screen density in DPI and styled for the specified theme.
Add also the `Resources.Theme` class and the `Context.getTheme()` method.
Checked that it works correctly in Kodi
> Add Resources.getDrawableForDensity method

- src/MediaCodecInfo.cpp
- src/MediaCodecInfo.h
to be used in Kodi.
Also add two new VP9 profile constants in the class.
> Add HEVC profile constants in MediaCodecInfo

- src/Activity.cpp
- src/Activity.h
- src/Context.cpp
- src/Context.h
- src/Resources.cpp
- src/Resources.h
- src/View.cpp
- src/View.h
Supercedes https://github.com/xbmc/libandroidjni/pull/42.
Let me know if I should close the other.
This PR contains the same `CJNIView::setBackgroundColor` and more.
This would allow for Kodi to find `View` objects by the resource name or ID.
Tested and it works.
I'll add the relevant changes to https://github.com/xbmc/xbmc/pull/22561
Or if we decide to simply just revert, this is example code: https://github.com/quietvoid/xbmc/commit/9e455a119ecab38a93163b6f7a3d3ec83184b016
> Add functions to allow obtaining specific views, and setting background color

- src/MediaFormat.cpp
- src/MediaFormat.h
Add these constants to use by name the Color range in the codec configuration
> Add Color range constants in MediaFormat

- src/ConnectivityManager.cpp
- src/ConnectivityManager.h
To find out about network events, use the [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback) class together with [ConnectivityManager.registerDefaultNetworkCallback(NetworkCallback)](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback))
> Listen to network events

- src/Context.cpp
- src/Display.cpp
- src/Display.h
Add [HDR types](https://developer.android.com/reference/android/view/Display.HdrCapabilities#constants_1) to be used in Kodi.
> HDR type constants

- src/Environment.cpp
- src/Environment.h
- src/StorageManager.cpp
- src/StorageManager.h
- src/StorageVolume.cpp
- src/StorageVolume.h
Add the `StorageManager.getPrimaryStorageVolume()` method along with the necessary `StorageVolume.getDirectory()` method to replace the deprecated `Environment.getExternalStorageDirectory()` method in API level 29.
Also, add some constants from the `Environment` class.
> Add StorageManager.getPrimaryStorageVolume method

- src/Context.cpp
- src/Context.h
- src/File.cpp
- src/File.h
- src/FileProvider.cpp
- src/FileProvider.h
- src/Intent.cpp
- src/Intent.h
Add `FileProvider` class and `getUriForFile()` method and other related changes needed to work:
- Add `Context.grantUriPermission()` method
- A `File` constructor
- Two `Intent` constants: `FLAG_GRANT_READ_URI_PERMISSION` and `FLAG_GRANT_WRITE_URI_PERMISSION`
> Share files using FileProvider

- src/Environment.cpp
- src/Environment.h
- src/NsdManager.h
This method returns whether the calling app has **All Files Access** on the primary shared/external storage media.
> Add Environment.isExternalStorageManager method
